### ISSUE TITLE
Template method "DateInt64" is missing

### ISSUE THREAD

**Issue by TimothyYe** [dingoblog/dingo#65]
From template file, I found it calls {{ DateInt64 .CreateTime "YYYY-MM-DD"}}.
But in func registerFuncMap() ,  DateInt64 is not registered.  Is it missing?

**Comment by dinever** [comment]
@TimothyYe Thanks for the feedback!

I've just submitted a quick fix

**Comment by TimothyYe** [comment]
I just fixed this issue a moment ago... Actually we can invoke method DateFormat instead of DateInt64...
Code is not pushed to GitHub yet, then I found that you already removed that sidebar template...   -_-#

**Comment by dinever** [comment]
Yeah, the sidebar template is actually unused. 😸 

It is actually called from [/view/default/default.html#L54](https://github.com/dingoblog/dingo/blob/master/view/default/default.html#L54) now.
